### ISSUE TITLE
[suggestion] _delete and _mtime flexibility

### ISSUE THREAD

**Issue by Ivshti** [kanekotic/Peer2Sync#29]
Regarding _delete, `datastorePut` always expects it passed, while from a client, you may not always set it unless you actually needed.

Regarding _mtime, it should also accept strings with the rationale of sending dates from JS:

``` javascript
JSON.stringify({ _mtime: new Date() });
// -> "{\"_mtime\":\"2016-08-24T15:07:36.271Z\"}"
```

**Comment by alvarolorentedev** [comment]
so splinting this into two: 
- _delete: makes sense, I will worked on it as soon as posible.
- _mtime: this is probably a failure in my side to express what the expected value as its undocumented. My personal opinion is a string could make it more complex to parse and generate, so will require more processing on the server side (and maybe in other languages). What the value of _mtime is supposed to be is a [POSIX time](https://en.wikipedia.org/wiki/Unix_time). most of the languages have support for this. And is the `defaultish` value that you will get also in JavaScript (but in JS its actually set in millisecons).

``` js
var time_ms = Date.now();
//or var time_ms = new Date().getTime();

var posix = Math.floor(time_ms / 1000);
// or var posix = time_ms / 1000 | 0;

//JSON.stringify({ _mtime: posix }) -> {"_mtime":1472107168}
```

for more insights on _mtime and posix please see this stackoverflow [post](http://stackoverflow.com/questions/221294/how-do-you-get-a-timestamp-in-javascript).

any thoughts? pros and cons?

**Comment by Ivshti** [comment]
This is interesting. I agree that strings are nasty in this case, since parsing an int is so much easier 

I like the timestamps in JS more over the POSIX time, since millisecond precision is important - even in this case, imagine if a user changes something twice in the space of a second, and we have a sync triggered twice. 
I assume this would create an issue with 32 bit ints, but perhaps 64 bit would be OK

**Comment by alvarolorentedev** [comment]
seems valid :+1: 

I did a bit of research and it is possible there are a few libraries that can be use even if there is a required future treatment [chrono](http://en.cppreference.com/w/cpp/chrono) and [posix](http://www.boost.org/doc/libs/1_61_0/doc/html/date_time/posix_time.html). 

For the current use a basic cast to `uint64_t` seems to be a good option. And I will modify the documentation to make sure this parameter is clearly expected as the time in posix format.

ps. [post](http://stackoverflow.com/questions/16177295/get-time-since-epoch-in-milliseconds-preferably-using-c11-chrono) on posix time in stackoverflow for future reference.

**Comment by alvarolorentedev** [comment]
@Ivshti please feel free to review the pull request to see if it matches what we have discussed.

**Comment by alvarolorentedev** [comment]
oull request has been merged
